server:
  port: 9191
spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
   hostname: localhost